name: Automated Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:  # bisa trigger manual

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python 3.12.7
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn mlflow==2.19.0

      # 4. Jalankan script preprocessing
      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Adi-Dwi-Pambudi.py

      # 5. Upload processed datasets sebagai artifact
      - name: Upload preprocessed datasets
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-datasets
          path: Exam_Score_preprocessing/
